//
// Created by Yile Liu on 4/29/20.
//

#ifndef PARALLEL_GRAPH_ATTENTION_NETWORK_FORWARD_PHASE_GAT_OMP_H
#define PARALLEL_GRAPH_ATTENTION_NETWORK_FORWARD_PHASE_GAT_OMP_H

#endif //PARALLEL_GRAPH_ATTENTION_NETWORK_FORWARD_PHASE_GAT_OMP_H
